{
  lib,
  pkgs,
  ...
}:
let
  # lemurs builds its session list by merging *two* sources: the executable
  # scripts in /etc/lemurs/wayland (defined below) and the `.desktop` entries
  # found under `wayland_sessions_path` / `x11.xsessions_path`, which the NixOS
  # module points at the generated `desktops` derivation. Only the scripts can
  # stamp RICE.
  #
  # RICE is the entirety of the per-session isolation: noctalia.service and
  # retroism-wallpaper.service are user-*global* unit files gated on
  # ConditionEnvironment, and the `systemd --user` manager outlives logins, so
  # a session started without a stamp does not get a neutral environment — it
  # inherits whatever the previous login left behind. Arriving from a Retroism
  # session that means RICE=retroism and DCONF_PROFILE are both still set, so
  # the retro wallpaper unit starts and every D-Bus-activated GTK app picks up
  # the retro dconf profile, inside the session the user selected as their
  # normal one. That is precisely the cross-session leak the design forbids.
  #
  # The `.desktop` entries are generated by the desktop packages themselves, so
  # there is no hook to make them stamp anything, so holding the invariant means
  # not offering them. Stated precisely, the invariant is "every greeter entry
  # that reaches graphical-session.target stamps RICE" — that target is what
  # pulls in the two gated units, so entries that never start it are outside the
  # claim. Two greeter entries are outside it today and safely so: the tty shell
  # (`environment_switcher.include_tty_shell`) and the Gamez script, which execs
  # gamescope directly and never starts the target (nothing pins it —
  # hyprland-session.target carries no [Install] section), leaving both gated
  # units unreachable there.
  #
  # Closing the `.desktop` sources takes *both* search paths, not just the
  # Wayland one: `wayland.wayland_sessions_path` and `x11.xsessions_path` both
  # track `services.displayManager.sessionPackages`. The x11 side is empty
  # today, so pointing it at an empty directory changes nothing live — it is
  # pre-emptive. Left at the module default, though, any future package shipping
  # an xsession `.desktop` would reappear as a non-stamping greeter entry, and
  # selecting it after a Retroism login would leave RICE=retroism and
  # DCONF_PROFILE live: noctalia suppressed, retro wallpaper started, inside a
  # session that is not the retro one. The module sets both with mkDefault, so
  # the two overrides below are all that is needed.
  emptySessions = pkgs.runCommand "lemurs-no-desktop-sessions" { } ''
    mkdir -p "$out/share/wayland-sessions" "$out/share/xsessions"
  '';
in
{

  services = {
    flatpak.enable = true;
    avahi.enable = true;
    chrony = {
      enable = true;
      enableNTS = true;
      servers = [
        "time.cloudflare.com"
        "ohio.time.system76.com"
      ];
    };
    resolved = {
      enable = true;
      settings.Resolve.DNSOverTLS = "opportunistic";
    };

    displayManager.lemurs = {
      enable = true;
      settings = {
        environment_switcher.include_tty_shell = true;
        # Both override the module's mkDefaults (`${desktops}/share/...`) so the
        # greeter offers only our scripts plus the tty shell. Rationale on
        # `emptySessions` above.
        wayland.wayland_sessions_path = "${emptySessions}/share/wayland-sessions";
        x11.xsessions_path = "${emptySessions}/share/xsessions";
      };
    };
    seatd.enable = true;
    printing.enable = true;
    udev = {
      extraRules = ''
        ACTION=="add", SUBSYSTEM=="usb", TEST=="power/control", ATTR{power/control}="on"
        ACTION=="add", SUBSYSTEM=="usb", TEST=="power/autosuspend" ATTR{power/autosuspend}="0"
        ACTION=="add", SUBSYSTEM=="usb", TEST=="power/autosuspend_delay_ms" ATTR{power/autosuspend_delay_ms}="0"
        # our Hyprland session runs under seatd and never attaches to a logind
        # seat, so the uaccess tag from libfido2's rules grants nothing; give
        # FIDO tokens (webauthn hidraw interface) to the seat group instead
        SUBSYSTEM=="hidraw", ENV{ID_FIDO_TOKEN}=="1", GROUP="seat", MODE="0660"
      '';
      packages = [
        pkgs.yubikey-personalization
        pkgs.libfido2
      ];
    };
    pcscd.enable = true;
    # sound
    pipewire = {
      enable = true;
      pulse.enable = true;
      audio.enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      wireplumber.enable = true;
    };
    # Maybe want to enable in the future
    # Enable the OpenSSH daemon.
    openssh.enable = true;
    # Execute shebangs like on normal linux (i.e #!/bin/bash)
    envfs.enable = true;
  };

  # A recent nixpkgs bump broke the s6-notify bridge in the stock seatd unit: seatd
  # 0.9.3 starts fine ("seatd started") but its Type=notify readiness never reaches
  # systemd, so systemd kills it on a 90s start-timeout loop. libseat then can't reach
  # a seat (the lemurs wayland session is registered seatless in logind), aquamarine
  # spins "Couldn't dispatch libseat events" forever, Hyprland melts and xdph crashes
  # in teardown. Run seatd directly with Type=exec so systemd treats exec as ready.
  systemd.services.seatd.serviceConfig = {
    Type = lib.mkForce "exec";
    ExecStart = lib.mkForce "${pkgs.seatd}/bin/seatd -u root -g seat -l info";
  };

  # services custom config
  environment = {
    # Named `Hyprland`, not `Hypr`, and the name is load-bearing. lemurs caches
    # the *title* of the last session in /var/cache/lemurs and re-selects it by
    # string match at the next login; a miss warns to the log and silently
    # leaves the selection at index 0, which is whatever fs::read_dir happens to
    # yield first (lemurs never sorts) — today `Gamez`. With the username also
    # cached, the default `focus_behaviour = FirstNonCached` puts the cursor in
    # the password field, so the session switcher is never looked at and Enter
    # launches that index-0 session. Matching the cached name verbatim is what
    # keeps the greeter pre-selecting this session. Rename only in lockstep with
    # /var/cache/lemurs.
    etc."lemurs/wayland/Hyprland" = {
      mode = "0755";
      enable = true;
      text = ''
        #! /bin/sh
        # Stamp the rice into the systemd user manager BEFORE the compositor
        # starts, so ConditionEnvironment gates see it and a stale value from
        # a previous session of the other rice is always overwritten.
        systemctl --user set-environment RICE=noctalia || true
        export RICE=noctalia
        # The retro session exports DCONF_PROFILE into this same user-wide
        # manager (it outlives the compositor across logins) and nothing else
        # ever clears it. Left set, every D-Bus-activated GTK app in this
        # session would pick up the retro dconf profile's theme/icons/cursor.
        #
        # This is *not* symmetric with the RICE stamp above, despite looking it.
        # RICE has a genuine second manager-level channel: the retro session's
        # rendered config bootstraps `dbus-update-activation-environment
        # --systemd RICE ...`, so RICE reaches the user manager by that route
        # too. There is no equivalent for clearing — that command can only set a
        # variable, never unset one — so the single `systemctl --user
        # unset-environment` below is DCONF_PROFILE's only manager-level clear,
        # and the `unset` after it reaches only this script's own descendants.
        # Residual risk: if the user manager is unreachable when this runs, the
        # `|| true` swallows the failure, RICE still lands via the compositor
        # bootstrap, but DCONF_PROFILE stays pointed at the retro profile — a
        # half-retro noctalia session (right shell, retro GTK theme/icons).
        systemctl --user unset-environment DCONF_PROFILE || true
        unset DCONF_PROFILE
        exec ${lib.getExe pkgs.hyprland}
      '';
    };
    etc."lemurs/wayland/Retroism" = {
      mode = "0755";
      enable = true;
      text = ''
        #! /bin/sh
        systemctl --user set-environment RICE=retroism || true
        export RICE=retroism
        # Path must track `programs.retroism.hyprland.deploy`, which writes to
        # `config.xdg.configHome`. lemurs sets XDG_CONFIG_HOME before running
        # this script, so read it here rather than assuming ~/.config; the
        # `:-` default keeps the script working if it is ever run by hand.
        exec ${lib.getExe pkgs.hyprland} --config "''${XDG_CONFIG_HOME:-$HOME/.config}/hypr/retroism.conf"
      '';
    };
    etc."lemurs/wayland/Gamez" = {
      mode = "0755";
      enable = true;
      text = ''
        #!/usr/bin/env bash
        set -xeuo pipefail

        gamescopeArgs=(
            --adaptive-sync # VRR support
            --hdr-enabled
            --mangoapp # performance overlay
            --fullscreen
            --nested-refresh 240
            --expose-wayland
            --force-grab-cursor
            --rt
            --steam
        )
        steamArgs=(
            -pipewire-dmabuf
            -tenfoot
        )
        mangoConfig=(
            cpu_temp
            gpu_temp
            ram
            vram
        )
        mangoVars=(
            MANGOHUD=1
            MANGOHUD_CONFIG="$(IFS=,; echo "''${mangoConfig[*]}")"
        )

        export "''${mangoVars[@]}"
        exec gamescope "''${gamescopeArgs[@]}" -- steam "''${steamArgs[@]}"
      '';
    };
  };
}
